#!/bin/sh
# test-cask-update.sh — deterministic tests for scripts/cask-update.sh.
#
# Public-safe: generates casks for a synthetic version (9.9.9) with fake
# hashes under a mktemp directory and asserts the generator's output
# shape, self-checks, and exit codes. No network, no build, no access to
# the real tap or release data.
#
# POSIX sh. Requires: ruby (the generator's self-check needs it).
#
# Usage: sh scripts/tests/test-cask-update.sh
# Exit codes: 0 = all tests pass, 1 = at least one test failed.

set -u

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
script_dir=$(dirname -- "$here")
cask_update="$script_dir/cask-update.sh"

[ -f "$cask_update" ] || { echo "error: $cask_update not found" >&2; exit 1; }
command -v ruby >/dev/null 2>&1 || { echo "error: ruby is required" >&2; exit 1; }

tmp=$(mktemp -d "${TMPDIR:-/tmp}/ltop-test-cask-update.XXXXXX") || exit 1
trap 'rm -rf "$tmp"' EXIT INT TERM

# Synthetic hashes (64 hex chars each).
SHA_ARM=$(printf '%064d' 0 | tr '0' 'a')
SHA_INTEL=$(printf '%064d' 0 | tr '0' 'b')

tests=0
failed=0

ok() {
    tests=$((tests + 1))
    echo "PASS $1"
}

bad() {
    tests=$((tests + 1))
    echo "FAIL $1"
    [ -n "${2:-}" ] && printf '%s\n' "$2" | sed 's/^/    /'
    failed=$((failed + 1))
}

# expect_rc <name> <wanted_rc> <cmd...>
expect_rc() {
    name=$1
    want=$2
    shift 2
    tests=$((tests + 1))
    "$@" > "$tmp/last.out" 2>&1
    rc=$?
    if [ "$rc" -eq "$want" ]; then
        echo "PASS $name"
    else
        echo "FAIL $name (exit $rc, wanted $want)"
        sed 's/^/    /' "$tmp/last.out" | tail -10
        failed=$((failed + 1))
    fi
}

# expect_grep <name> <pattern> <file>
expect_grep() {
    name=$1
    pattern=$2
    file=$3
    tests=$((tests + 1))
    if grep -q "$pattern" "$file"; then
        echo "PASS $name"
    else
        echo "FAIL $name (pattern not found: $pattern)"
        failed=$((failed + 1))
    fi
}

# expect_absent <name> <pattern> <file>
expect_absent() {
    name=$1
    pattern=$2
    file=$3
    tests=$((tests + 1))
    if grep -q "$pattern" "$file"; then
        echo "FAIL $name (unexpected match: $pattern)"
        grep -n "$pattern" "$file" | sed 's/^/    /' | head -5
        failed=$((failed + 1))
    else
        echo "PASS $name"
    fi
}

# =============================================================================
# T1: two-arch ad-hoc generation
# =============================================================================

mkdir -p "$tmp/out/tap/Casks" "$tmp/out/release/homebrew/Casks"
expect_rc "T1 two-arch ad-hoc exits 0" 0 sh "$cask_update" 9.9.9 \
    "$SHA_ARM" "$SHA_INTEL" ad-hoc \
    "$tmp/out/tap/Casks/ltop.rb" "$tmp/out/release/homebrew/Casks/ltop.rb.template"
cask1="$tmp/out/tap/Casks/ltop.rb"
tmpl1="$tmp/out/release/homebrew/Casks/ltop.rb.template"

expect_grep "T1 cask: arch stanza" 'arch arm: "arm64", intel: "x86_64"' "$cask1"
expect_grep "T1 cask: version" 'version "9.9.9"' "$cask1"
expect_grep "T1 cask: arm sha" "sha256 arm:   \"$SHA_ARM\"" "$cask1"
expect_grep "T1 cask: intel sha" "intel: \"$SHA_INTEL\"" "$cask1"
expect_grep "T1 cask: interpolated url" 'ltop-v#{version}-macos-#{arch}.zip' "$cask1"
expect_grep "T1 cask: interpolated binary" 'ltop-v#{version}-macos-#{arch}/ltop' "$cask1"
expect_grep "T1 cask: livecheck github_latest" 'strategy :github_latest' "$cask1"
expect_grep "T1 cask: big sur floor" 'depends_on macos: :big_sur' "$cask1"
expect_grep "T1 cask: ad-hoc caveats" 'ad-hoc signed' "$cask1"
expect_grep "T1 cask: arm sha in caveats" "$SHA_ARM" "$cask1"
expect_grep "T1 cask: intel sha in caveats" "$SHA_INTEL" "$cask1"
expect_absent "T1 cask: no arch requirement line" '^  depends_on arch:' "$cask1"
expect_absent "T1 cask: no placeholders" 'REPLACE\|PLACEHOLDER\|TODO\|FIXME' "$cask1"
expect_absent "T1 cask: no stale signing claim" 'Developer-ID signed and' "$cask1"

# template: generated header + identical region
expect_grep "T1 template: generated header" 'Generated by scripts/cask-update.sh for version 9.9.9 (signing: ad-hoc)' "$tmpl1"
expect_grep "T1 template: reference-copy note" 'REFERENCE COPY' "$tmpl1"
if [ "$(sed -n '/^cask "ltop" do$/,/^end$/p' "$cask1")" = "$(sed -n '/^cask "ltop" do$/,/^end$/p' "$tmpl1")" ]; then
    ok "T1 template region byte-identical to cask"
else
    bad "T1 template region byte-identical to cask"
fi

# =============================================================================
# T2: single-arch arm64 (unsigned)
# =============================================================================

mkdir -p "$tmp/out/tap2/Casks" "$tmp/out/release2/homebrew/Casks"
expect_rc "T2 arm64-only unsigned exits 0" 0 sh "$cask_update" 9.9.9 \
    "$SHA_ARM" - unsigned \
    "$tmp/out/tap2/Casks/ltop.rb" "$tmp/out/release2/homebrew/Casks/ltop.rb.template"
cask2="$tmp/out/tap2/Casks/ltop.rb"
expect_absent "T2 no arch stanza" 'arch arm:' "$cask2"
expect_grep "T2 plain sha256" "sha256 \"$SHA_ARM\"" "$cask2"
expect_grep "T2 url bakes arm64" 'ltop-v#{version}-macos-arm64.zip' "$cask2"
expect_grep "T2 binary bakes arm64" 'ltop-v#{version}-macos-arm64/ltop' "$cask2"
expect_grep "T2 unsigned caveats" 'NOT signed and NOT notarized' "$cask2"
expect_grep "T2 single-arch sha line in caveats" "$SHA_ARM--ltop-v9.9.9-macos-arm64.zip" "$cask2"

# =============================================================================
# T3: single-arch x86_64 (developer-id)
# =============================================================================

mkdir -p "$tmp/out/tap3/Casks" "$tmp/out/release3/homebrew/Casks"
expect_rc "T3 x86_64-only developer-id exits 0" 0 sh "$cask_update" 9.9.9 \
    - "$SHA_INTEL" developer-id \
    "$tmp/out/tap3/Casks/ltop.rb" "$tmp/out/release3/homebrew/Casks/ltop.rb.template"
cask3="$tmp/out/tap3/Casks/ltop.rb"
expect_grep "T3 arch requirement" 'depends_on arch: :x86_64' "$cask3"
expect_grep "T3 url bakes x86_64" 'ltop-v#{version}-macos-x86_64.zip' "$cask3"
expect_grep "T3 developer-id caveats" 'Developer-ID signed and' "$cask3"
expect_absent "T3 no unblock procedure" 'unblock the binary' "$cask3"

# =============================================================================
# T4: idempotency (two runs, byte-identical outputs)
# =============================================================================

mkdir -p "$tmp/out/tap4a/Casks" "$tmp/out/tap4b/Casks" "$tmp/out/tmpl4a/homebrew/Casks" "$tmp/out/tmpl4b/homebrew/Casks"
sh "$cask_update" 9.9.9 "$SHA_ARM" "$SHA_INTEL" ad-hoc \
    "$tmp/out/tap4a/Casks/ltop.rb" "$tmp/out/tmpl4a/homebrew/Casks/ltop.rb.template" > /dev/null 2>&1
sh "$cask_update" 9.9.9 "$SHA_ARM" "$SHA_INTEL" ad-hoc \
    "$tmp/out/tap4b/Casks/ltop.rb" "$tmp/out/tmpl4b/homebrew/Casks/ltop.rb.template" > /dev/null 2>&1
tests=$((tests + 1))
if cmp -s "$tmp/out/tap4a/Casks/ltop.rb" "$tmp/out/tap4b/Casks/ltop.rb" \
    && cmp -s "$tmp/out/tmpl4a/homebrew/Casks/ltop.rb.template" "$tmp/out/tmpl4b/homebrew/Casks/ltop.rb.template"; then
    echo "PASS T4 idempotent outputs"
else
    echo "FAIL T4 idempotent outputs"
    failed=$((failed + 1))
fi

# =============================================================================
# T5: usage errors (exit 2)
# =============================================================================

expect_rc "T5 wrong arg count" 2 sh "$cask_update" 9.9.9 "$SHA_ARM"
expect_rc "T5 bad version" 2 sh "$cask_update" v9.9.9 "$SHA_ARM" - ad-hoc "$tmp/out/tap/Casks/ltop.rb" "$tmp/out/release/homebrew/Casks/ltop.rb.template"
expect_rc "T5 both shas dash" 2 sh "$cask_update" 9.9.9 - - ad-hoc "$tmp/out/tap/Casks/ltop.rb" "$tmp/out/release/homebrew/Casks/ltop.rb.template"
expect_rc "T5 bad sha" 2 sh "$cask_update" 9.9.9 zzzz - ad-hoc "$tmp/out/tap/Casks/ltop.rb" "$tmp/out/release/homebrew/Casks/ltop.rb.template"
expect_rc "T5 bad signing" 2 sh "$cask_update" 9.9.9 "$SHA_ARM" - bogus "$tmp/out/tap/Casks/ltop.rb" "$tmp/out/release/homebrew/Casks/ltop.rb.template"
expect_rc "T5 missing parent dir" 2 sh "$cask_update" 9.9.9 "$SHA_ARM" - ad-hoc "$tmp/out/nope/Casks/ltop.rb" "$tmp/out/release/homebrew/Casks/ltop.rb.template"
expect_rc "T5 bare filename cask path" 2 sh "$cask_update" 9.9.9 "$SHA_ARM" - ad-hoc ltop.rb "$tmp/out/release/homebrew/Casks/ltop.rb.template"

# =============================================================================
# T6: uppercase hashes are normalized to lowercase
# =============================================================================

mkdir -p "$tmp/out/tap6/Casks" "$tmp/out/release6/homebrew/Casks"
UPPER_ARM=$(printf '%s' "$SHA_ARM" | tr 'a-d' 'A-D')
expect_rc "T6 uppercase sha exits 0" 0 sh "$cask_update" 9.9.9 \
    "$UPPER_ARM" "$SHA_INTEL" ad-hoc \
    "$tmp/out/tap6/Casks/ltop.rb" "$tmp/out/release6/homebrew/Casks/ltop.rb.template"
expect_grep "T6 sha lowercased" "sha256 arm:   \"$SHA_ARM\"" "$tmp/out/tap6/Casks/ltop.rb"

# =============================================================================

echo "---"
echo "test-cask-update: $tests tests, $failed failed"
if [ "$failed" -ne 0 ]; then
    exit 1
fi
echo "test-cask-update: all tests PASS"
exit 0
